feat: add scx-scheds
This adds support for scx-scheds, same package in bazzite. This will only work on fsync kernels like the one in `:latest`. 

Running the tools on stock kernels is a noop so we're safe there:

```
❯ sudo scx_bpfland 
[sudo] password for jorge: 
23:30:09 [INFO] scx_bpfland 1.0.4 x86_64-unknown-linux-gnu SMT on
Error: sched_ext_ops.dump() missing, kernel too old?
```